spring:
  datasource:
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sweater-app
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: validate
  security:
    user:
      name: admin
      password: admin
    recaptcha:
      site-key: 6LcRX6wkAAAAAHI55z77IRNepMwg42699X6dVk1H
      secret-key: 6LcRX6wkAAAAAHJ4SYhpioTK9xetQHYa_OyRbAg6

  devtools:
    restart:
      enabled: true